name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Build
        run: .github/workflows/build_release.sh
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            ./*.tar.gz
